mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('deepthoughts/', views.DeepthoughtsView.as_view(), name='deepthoughts'),
    path('deepthoughts/submit/', views.submit, name='submit'),
    path('deepthoughts/list/', views.ListView.as_view(), name='list'),
    
]

polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text


class Deepthoughts(models.Model):
    text = models.CharField(max_length=200)
    def __str__(self):
        return (self.text)

polls/views.py
from django.utils import timezone
from django.views import generic
from django.urls import reverse
from django.shortcuts import get_object_or_404, render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect

from .models import Choice, Question, Deepthoughts

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class DeepthoughtsView(generic.CreateView):
    model = Deepthoughts
    template_name = 'polls/deepthoughts.html'
    fields = ['text']
    
class ListView(generic.ListView):
    context_object_name = 'latest_thoughts_list'
    template_name = 'polls/list.html'
    def get_queryset(self):
        return Deepthoughts.objects.all()

def submit(request):
    d_text = request.POST.get('content')
    if d_text == '':
        return render(request, 'polls/deepthoughts.html')
    tmp = Deepthoughts(text = d_text)
    tmp.save()
    return HttpResponseRedirect(reverse('polls:list'))

polls/templates/polls/deepthoughts.html
<ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Polls</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Deepthoughts</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
<center>
<h1>deepthoughts</h1>
<form action = "{% url 'polls:submit' %}" method = "POST"> 
    {% csrf_token %}
    <label>Content:</label><br>
    <input type="text" name = "content"><br><br>
    <input type="submit" value="Submit">
</form>
</center>
<div class="col-md-4 d-flex align-items-center">
    <span class="text-muted"> Li</span>
</div>

polls/templates/polls/detail.html
<ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Polls</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Deepthoughts</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>



 
<div class = 'container', align = 'center'>
    <div class = 'row'>
        <h1>{{ question.question_text }}</h1>
    </div>
    <div class = 'row'>
        <ul>
            {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
            {% endfor %}
        </ul>
    </div>
     
    <form action="{% url 'polls:vote' question.id %}" method="post" class = 'row'>
    {% csrf_token %}
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p >{% endif %}
        {% for choice in question.choice_set.all %}
        <div class = 'col'>
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label class="btn btn-primary", for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        </div> 
        {% endfor %}
    <div class = 'col'>
    <input type="submit" value="Vote">
    </div>
    </form>
</div>

<div class="col-md-4 d-flex align-items-center">
    <span class="text-muted"> Li</span>
</div>

polls/templates/polls/index.html
<ul class="nav nav-pills">
        <li class="nav-item">< a href="#" class="nav-link active" aria-current="page">Home</ a></li>
        <li class="nav-item">< a href="#" class="nav-link">Polls</ a></li>
        <li class="nav-item">< a href="#" class="nav-link">Deepthoughts</ a></li>
        <li class="nav-item">< a href="#" class="nav-link">FAQs</ a></li>
        <li class="nav-item">< a href="#" class="nav-link">About</ a></li>
      </ul>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>< a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</ a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p >
{% endif %}

<div class="col-md-4 d-flex align-items-center">
    <span class="text-muted"> Li</span>
</div>

polls/templates/polls/list.html
<ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Polls</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Deepthoughts</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>




 
<center>
<h1>Deepthoughts List</h1>

<table class="table">
    <thead>
      <tr>
        <th scope="col">Content</th>
      </tr>
    </thead>
    <tbody>
    {% for i in latest_thoughts_list %}
      <tr>
        <td>{{ i.text }}</td>
      </tr>
    {% endfor %}
    </tbody>
</table>

<div class="col-md-4 d-flex align-items-center">
    <span class="text-muted"> @ Zhiang Li</span>
</div>

polls/templates/polls/results.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
<head>
<style>
    .fixed-header{
        top : 0;
    }
    .fixed-footer{
        bottom : 0;
    }
</style>
</head>
<div class = 'fixed-header'>
<div class = 'container'>


<ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Polls</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Deepthoughts</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
</div>
</div>
<div align = 'center'>
<h1>{{ question.question_text }}</h1>


<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Choice</th>
        <th scope="col">votes</th>
      </tr>
    </thead>
    <tbody>
    {% for choice in question.choice_set.all %}
      <tr>
        <th scope="row">{{choice.id}}</th>
        <td>{{ choice.choice_text }}</td>
        <td>{{ choice.votes }}</td>
      </tr>
    {% endfor %}
    </tbody>
</table>

</div>
<div class = 'fixed-footer'>
<div class = 'container'>
<div class="col-md-4 d-flex align-items-center">
    <span class="text-muted"> Li</span>
</div>
</div>